config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sessions/new'

  resources :submissions

  mount Sidekiq::Web => '/sidekiq'

  namespace 'admin' do
    resource 'contest'
    put 'contest/start',  to: 'contests#start', as: :start_contest

    get 'scoreboard' => 'scoreboard#show', as: :contest_scoreboard

    resources :problems

    resources :attachments, only: [:destroy]

    resources :accounts, only: [:index, :new, :create]
  end

  resources :teams, only: :show, as: :team_contest_scoreboard

  resources :problems, only: [:index, :show]

  resources :attachments, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  get 'login',  to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get "/admin" => redirect("/admin/contest")

  root to: 'problems#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :contest
  has_many :submissions

  def self.authenticate(username, token)
    Account.find_by(username: username, password: token)
  end
end

# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  username   :string
#  password   :string
#  contest_id :integer
#  admin      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/admin/accounts_controller.rb
module Admin
  class AccountsController < AdminController
    def index
      @contest  = Contest.instance
      @accounts = @contest.accounts
    end

    def new
      @contest = Contest.instance
      @account = @contest.accounts.build
    end

    def create
      @contest = Contest.instance
      @account = @contest.accounts.build account_params.merge(password: TokenPhrase.generate)

      if @account.save
        redirect_to admin_accounts_path
      else
        render action: 'new'
      end
    end

    private

    def account_params
      params.require(:account).permit(:name, :username)
    end
  end
end

app/views/admin/accounts/_account.html.erb
<section class='account card'>
  <header class='card-header'>
    <h3><%= account.name %></h3>
  </header>

  <div class=card-block>
    <strong><%= account.username %></strong>
  </div>

  <footer class='card-footer'><span class=token><%= account.password %></span></footer>
</section>

app/views/admin/accounts/index.html.erb
<h1><%= @contest.name %> Accounts</h1>

<%= link_to "Add New Account", new_admin_account_path,
    class: "btn btn-primary #{'disabled' if @contest.in_progress?}",
    disabled: @contest.in_progress? %>

<%= link_to "Back", admin_path, class: 'btn btn-secondary' %>

<hr />

<%= render @accounts, partial: 'admin/accounts/account' %>

app/views/admin/accounts/new.html.erb
<h1><%= @contest.name %>: Create new Account</h1>

<%= simple_form_for [:admin, @account] do |form| %>

  <div class='form-controls'>
    <%= form.input :name %>
    <%= form.input :username %>
  </div>

  <div class='form-actions'>
    <%= form.button :submit %>
  </div>

<% end %>