config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sessions/new'

  resources :submissions

  mount Sidekiq::Web => '/sidekiq'

  namespace 'admin' do
    resource 'contest'
    put 'contest/start',  to: 'contests#start', as: :start_contest

    get 'scoreboard' => 'scoreboard#show', as: :contest_scoreboard

    resources :problems

    resources :attachments, only: [:destroy]

    resources :accounts, only: [:index, :new, :create]
  end

  resources :teams, only: :show, as: :team_contest_scoreboard

  resources :problems, only: [:index, :show]

  resources :attachments, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  get 'login',  to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get "/admin" => redirect("/admin/contest")

  root to: 'problems#index'
end

app/models/contest.rb
class Contest < ApplicationRecord
  has_many :problems
  has_many :accounts

  def self.instance
    order(:created_at).reverse.first
  end

  def start(time: Time.current.utc)
    self.started_at = time
    save!
  end

  def in_progress?
    !!started_at
  end
end

# == Schema Information
#
# Table name: contests
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  started_at :datetime
#

app/controllers/admin/contests_controller.rb
module Admin
  class ContestsController < AdminController
    def show
      @contest = Contest.instance
    end

    def edit
      @contest = Contest.instance
    end

    def update
      @contest = Contest.instance

      if @contest.update contest_params
        redirect_to admin_contest_path
      else
        render :edit
      end
    end

    def start
      @contest = Contest.instance

      @contest.start

      @contest.save
      flash[:success] = "The contest has started"

      redirect_to admin_contest_path
    end

  private
    def contest_params
      params.require(:contest).permit(:name)
    end
  end
end

app/views/admin/contests/edit.html.erb
<h1>Name your contest</h1>

<%= simple_form_for [:admin, @contest], url: admin_contest_path do |form| %>

  <div class="form-controls">
    <%= form.input :name %>
  </div>

  <div class='form-actions'>
    <%= form.button :submit %>
  </div>

<% end %>

app/views/admin/contests/show.html.erb
<section class=jumbotron>
  <h1><%= @contest.name %></h1>

  <hr />

  <% if @contest.started_at %>
    <h2>started at <%= @contest.started_at.to_s %></h2>

    <div class='btn-toolbar justify-content-between'>
      <%= link_to "Scoreboard", admin_contest_scoreboard_path, class: 'btn btn-primary' %>

      <div class='btn-group'>
        <span class='input-group-addon'><%= @contest.problems.count %></span>
        <%= link_to 'Problems', admin_problems_path, class: 'btn btn-secondary' %>
      </div>
      <div class='btn-group'>
        <span class='input-group-addon'><%= @contest.accounts.count %></span>
        <%= link_to 'Accounts', admin_accounts_path, class: 'btn btn-secondary' %>
      </div>
      <div class='btn-group'>
        <span class='input-group-addon'><%= Submission.count %></span>
        <%= link_to 'Submissions', "#",
          disabled: !@contest.in_progress?,
          class: "btn btn-secondary #{'disabled' unless @contest.in_progress?}" %>
      </div>

      <div class='input-group'>
        <%= button_to "Stop Contest", "#", method: 'put', class: 'btn btn-danger disabled' %>
      </div>
    </div>

  <% else %>

    <div class='btn-toolbar justify-content-between'>
      <%= link_to "Edit Contest", edit_admin_contest_path, class: 'btn btn-secondary' %>

      <div class='btn-group'>
        <span class='input-group-addon'><%= @contest.problems.count %></span>
        <%= link_to 'Problems', admin_problems_path, class: 'btn btn-secondary' %>
      </div>
      <div class='btn-group'>
        <span class='input-group-addon'><%= @contest.accounts.count %></span>
        <%= link_to 'Accounts', admin_accounts_path, class: 'btn btn-secondary' %>
      </div>
      <div class='btn-group'>
        <span class='input-group-addon'><%= Submission.count %></span>
        <%= link_to 'Submissions', "#", class: 'btn btn-secondary disabled' %>
      </div>

      <div class='input-group'>
        <%= button_to "Start Contest", admin_start_contest_path, method: 'put', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
</section>