config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sessions/new'

  resources :submissions

  mount Sidekiq::Web => '/sidekiq'

  namespace 'admin' do
    resource 'contest'
    put 'contest/start',  to: 'contests#start', as: :start_contest

    get 'scoreboard' => 'scoreboard#show', as: :contest_scoreboard

    resources :problems

    resources :attachments, only: [:destroy]

    resources :accounts, only: [:index, :new, :create]
  end

  resources :teams, only: :show, as: :team_contest_scoreboard

  resources :problems, only: [:index, :show]

  resources :attachments, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  get 'login',  to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get "/admin" => redirect("/admin/contest")

  root to: 'problems#index'
end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :attachments, as: :attachable
  has_many :submissions
  belongs_to :contest

  # FIXME: probably need a validator for ensuring unique names inside a contest
  # validates :name, presence: true

  WHITESPACE_RULES = ["plain diff", "ignore all whitespace", "ignore leading whitespace", "ignore trailing whitespace"]

  def uploaded_files_dir
    self.class.files_base.join("problems/#{id}")
  end

  def input_file
    # FIXME? does the `first` invocation here need to be fixed?
    attachments.find_by(attachment_type: "sample_in").path
  end

  def output
    output_file = attachments.where(attachment_type: "sample_out").first.path

    Pathname.new(output_file).read
  end

  def self.create_from_files!(name:, contest:, output_file:, input_file: nil, **options)
    input_file  = Pathname.new(input_file)
    output_file = Pathname.new(output_file)

    # FIXME: actually handle the handout_file parameter

    Problem.transaction do
      problem = Problem.create!(
        contest:   contest,
        name:      name,
        has_input: input_file.present?,
      )

      input_attachment = Attachment.create!(
        original_filename: input_file.basename,
        attachment_type:   'sample_in',
        attachable:        problem,
      )

      input_attachment.with_file('wb') do |attach_file|
        attach_file.write(input_file.read)
      end

      output_attachment = Attachment.create!(
        original_filename: output_file.basename,
        attachment_type:   'sample_out',
        attachable:        problem,
      )

      output_attachment.with_file('wb') do |attach_file|
        attach_file.write(output_file.read)
      end

      problem.save!

      problem
    end
  end
end

# == Schema Information
#
# Table name: problems
#
#  id              :integer          not null, primary key
#  name            :string
#  description     :text
#  contest_id      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  timeout         :integer
#  has_input       :boolean
#  auto_judge      :boolean
#  ignore_case     :boolean
#  whitespace_rule :string           default("plain diff")
#

app/controllers/admin/problems_controller.rb
module Admin
  class ProblemsController < AdminController
    ATTACHMENT_TYPES = %w(handout sample_in sample_out)

    # FIXME not testing
    def index
      @contest  = Contest.instance
      @problems = @contest.problems
    end

    def show
      @contest = Contest.instance
      @problem = @contest.problems.find(params[:id])
    end

    def new
      @contest = Contest.instance
      @problem = @contest.problems.build

      @attachments = ATTACHMENT_TYPES.map do |type|
        Attachment.new(attachment_type: type)
      end
    end

    def edit
      @contest     = Contest.instance
      @problem     = Problem.find_by_id(params[:id])
      @attachments = ATTACHMENT_TYPES.map do |type|
        Attachment.new(attachment_type: type)
      end
    end

    def update
      @problem = Problem.find_by_id(params[:id])

      @problem.update_attributes(problem_parameters)

      if params[:problem][:attachment]
        ATTACHMENT_TYPES.each do |type|
          add_attachment(params[:problem][:attachment][type], type)
        end
      end

      redirect_to @problem, notice: 'Problem updated'
    end

    def create
      @contest = Contest.instance
      @problem = @contest.problems.build problem_parameters

      if @problem.save
        if params[:problem][:attachment]
          ATTACHMENT_TYPES.each do |type|
            add_attachment(params[:problem][:attachment][type], type)
          end
        end

        redirect_to problem_path @problem
      else
        render action: 'new'
      end
    end

    def destroy
      problem = Problem.find_by_id(params[:id])

      if problem
        problem.destroy
        redirect_to(problems_path, notice: 'Problem removed.')
      else
        redirect_to(problems_path, status: 404, notice: 'Not found')
      end
    end

    private

    def add_attachment(io, label)
      return unless io

      attachment = @problem.attachments.build(original_filename: io.original_filename,
                                              content_type:      io.content_type,
                                              attachment_type:   label)

      attachment.with_file('w') do |file|
        file.write(io.read)
      end

      attachment.save # save after writing in case something goes wrong
    end

    def problem_parameters
      params.require(:problem).permit(:name,
                                      :description,
                                      :timeout,
                                      :has_input,
                                      :auto_judge,
                                      :ignore_case,
                                      :whitespace_rule)
    end
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  def index
    @problems = Problem.all.map do |problem|
      ProblemPresenter.new(problem)
    end
  end

  def show
    @contest = Contest.instance
    @problem = ProblemPresenter.new(@contest.problems.find(params[:id]))
  end
end

app/views/admin/problems/_form.html.erb
<%= simple_form_for [:admin, @problem] do |form| %>
  <div class="form-controls">
    <%= form.input :name %>
    <%= form.input :description, type: :text %>

    <%= form.input :timeout, as: :integer, label: 'Timeout (seconds)' %>

    <%= form.input :has_input %>
    <%= form.input :auto_judge %>
    <%= form.input :ignore_case %>

    <%= form.input :whitespace_rule, as: :select,
      collection: Problem::WHITESPACE_RULES %>

    <h3>Upload Attachments</h3>
    <% @attachments.each do |attachment| %>
      <%= form.simple_fields_for(attachment) do |a| %>
        <%= a.input attachment.attachment_type, as: :file %>
      <% end %>
    <% end %>
  </div>

  <div class="form-actions">
    <%= form.button :submit %>
  </div>
<% end %>

<br />
<%= link_to('Back', problems_path) %>

app/views/admin/problems/edit.html.erb
<h1>Edit Problem <%= @problem.id %></h1>
<%= render 'admin/problems/form' %>

app/views/admin/problems/index.html.erb
<h1>Problems</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Name</th>
      <th scope="col">Timeout</th>
      <th scope="col">Has Input?</th>
      <th scope="col">Auto Judge?</th>
      <th scope="col">Ignore Case?</th>
      <th scope="col">Whitespace Handling</th>
      <th class="actions" scope="col" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.id %></td>
        <th scope="row"><%= problem.name %></th>
        <td><%= problem.timeout %></td>
        <td><%= problem.has_input %></td>
        <td><%= problem.auto_judge %></td>
        <td><%= problem.ignore_case %></td>
        <td><%= problem.whitespace_rule %></td>
        <td><%= link_to 'Show', [:admin, problem] %></td>
        <td><%= link_to 'Edit', edit_admin_problem_path(problem) %></td>
        <td><%= link_to 'Delete',
                        admin_problem_path(problem),
                        method: :delete,
                        data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "New Problem", new_admin_problem_path, class: 'btn btn-primary' %>
<%= link_to "Back to Contest", admin_contest_path, class: 'btn btn-secondary' %>

app/views/admin/problems/new.html.erb
<h1>Create a New Contest Problem</h1>
<%= render 'admin/problems/form' %>

app/views/admin/problems/show.html.erb
<h1><%= @problem.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @problem.description %>
</p>

<p>
  <strong>Timeout:</strong>
  <%= @problem.timeout %>
</p>

<p>
  <strong>Has Input?</strong>
  <%= @problem.has_input %>
</p>

<p>
  <strong>Auto Judge?</strong>
  <%= @problem.auto_judge %>
</p>

<p>
  <strong>Ignore Case?</strong>
  <%= @problem.ignore_case %>
</p>

<p>
  <strong>Whitespace Rule:</strong>
  <%= @problem.whitespace_rule %>
</p>

<table class="table table-striped">
  <caption>Attachments</caption>
  <thead>
    <tr>
      <th scope="col">Filename</th>
      <th scope="col">Type</th>
      <th scope="col">Content Type</th>
      <th class="actions" scope="col" colspan="2">Actions</th>
    </tr>
  </thead>

  <% @problem.attachments.each do |attachment| %>
      <tbody>
        <tr>
          <th scope="row"><%= attachment.original_filename %></th>
          <td><%= attachment.attachment_type %></td>
          <td><%= attachment.content_type %></td>
          <td><%= link_to 'Download', attachment %></td>
          <td><%= link_to 'Delete',
                          admin_attachment_path(attachment),
                          method: :delete,
                          data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      </tbody>
    <br>
  <% end %>
</table>

<%= link_to 'Edit', edit_admin_problem_path(@problem), class: 'btn btn-primary' %>
<%= link_to 'Back', admin_problems_path, class: 'btn btn-secondary' %>