config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'sessions/new'

  resources :submissions

  mount Sidekiq::Web => '/sidekiq'

  namespace 'admin' do
    resource 'contest'
    put 'contest/start',  to: 'contests#start', as: :start_contest

    get 'scoreboard' => 'scoreboard#show', as: :contest_scoreboard

    resources :problems

    resources :attachments, only: [:destroy]

    resources :accounts, only: [:index, :new, :create]
  end

  resources :teams, only: :show, as: :team_contest_scoreboard

  resources :problems, only: [:index, :show]

  resources :attachments, only: [:show]

  resources :sessions, only: [:new, :create, :destroy]
  get 'login',  to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  get "/admin" => redirect("/admin/contest")

  root to: 'problems#index'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse mb-4">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#">Milton</a>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to "Problems", problems_path, class: 'nav-link' %>
      </li>
      <li class='nav-item'>
        <%= link_to "New Submission", new_submission_path, class: 'nav-link' %>
      </li>
      <% if current_account && current_account.admin? %>
      <li class="nav-item">
        <%= link_to "Manage", admin_contest_path, class: 'nav-link' %>
      </li>
      <% end %>
      <% if current_account %>
        <li class="nav-item">
          <%= link_to "Logout", logout_path, class: 'nav-link' %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Milton</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller.controller_name %>">
    <%= render 'layouts/navbar' %>


    <main class=container>
      <% flash.each do |key, value| -%>
        <%= content_tag :div, value, class: "alert alert-#{flash_category(key)}" %>
      <% end -%>

      <%= yield %>
    </main>
  </body>
</html>